name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Image from source and test it 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile 
    - name: Check out the repo
      uses: actions/checkout@v2     
    - name: Docker Login
      uses: docker/login-action@v1       
      with:
          username: icyak
          password: ${{ secrets.DOCKERHUBPASS }}
    - name: Push to Docker Hub
#      uses: docker/build-push-action@v1
#      with:
#        push: true
#        tag: latest
      uses: docker/build-push-action@v1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: icyak/backend-multi:latest
