name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Build the Docker image
    - run: docker build . --file Dockerfile --tag icyak/backend-multi:latest #--tag icyak/ll-nginx:latest
    - uses: actions/setup-node@v1
    - uses: docker/build-push-action@v1
      with:
        push: true
        username: icyak
        password: ${{ secrets.DOCKERHUBPASS }}
#        tags: icyak/nginx-test:latest
